import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'
  const [audioUrl, setAudioUrl] = useState(null);

  const minus = () => {
    chrome.runtime.sendMessage({ type: 'END_VO' }, async (response) => {
      console.log(response);
      setAudioUrl(response.audioUrl);

      await fetch('http://localhost:3000/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(response)
      })
        .then(res => {
           res.arrayBuffer()
            .then((result) => {
              // Create a download link for the video
              const a = document.createElement("a");
              a.href = videoUrl;
              a.download = URL.createObjectURL(new Blob([result], { type: "video:mp4" }));
              a.click();
            })
        });
    

      return true;
    })
  }

  const add = async () => {
    // Send message to background to start recording
    chrome.runtime.sendMessage({
      type: 'START_VO'
    })
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      { audioUrl && (
        <audio src={audioUrl} controls={true}></audio>
      )}
    </main>
  )
}

export default Popup
