import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  let mediaRecorder;
  let audioChunks = [];

  const minus = () => {
    if (mediaRecorder && mediaRecorder.state !== 'inactive') {
      mediaRecorder.stop();
      console.log('Recorder Stopped');
    }
  }

  const add = async () => {
    navigator.mediaDevices.getUserMedia({ audio: true })
      .then(stream => {
        mediaRecorder = new MediaRecorder(stream);
        audioChunks = [];

        mediaRecorder.ondataavailable = event => {
          if (event.data.size > 0) {
            audioChunks.push(event.data);
            console.log('audio recording');
          }
        };

        mediaRecorder.onstop = () => {
          const audioBlob = new Blob(audioChunks, { type: 'audio/webm' });
          const audioUrl = URL.createObjectURL(audioBlob);

          const link = document.createElement('a');
          link.href = audioUrl;
          link.download = 'recording.webm';
          link.click();
        };

        mediaRecorder.start();
        console.log(mediaRecorder);
      })
      .catch(err => {
        console.error('Error accessing mic:', err);
    });
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
