import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'
  const [audioUrl, setAudioUrl] = useState(null);

  const minus = () => {
    chrome.runtime.sendMessage({ type: 'END_VO' }, (response) => {
      console.log(response.audioUrl);
      setAudioUrl(response.audioUrl);

      const downloadLink = document.createElement('a');
      downloadLink.href = response.audioUrl;
      downloadLink.download = 'recorded_audio.webm';
      downloadLink.click();

      return true;
    })
  }

  const add = async () => {
    // Send message to background to start recording
    chrome.runtime.sendMessage({
      type: 'START_VO'
    })
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      { audioUrl && (
        <audio src={audioUrl} controls={true}></audio>
      )}
    </main>
  )
}

export default Popup
